// <auto-generated />
using BibliotecaMetropolis.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaMetropolis.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020162743_AjusteRelacionesYTablas")]
    partial class AjusteRelacionesYTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaMetropolis.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdAutor");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.AutoresRecursos", b =>
                {
                    b.Property<int>("IdRec")
                        .HasColumnType("int");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.HasKey("IdRec", "IdAutor");

                    b.HasIndex("IdAutor");

                    b.ToTable("AutoresRecursos");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Editorial", b =>
                {
                    b.Property<int>("IdEdit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEdit"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEdit");

                    b.ToTable("Editorial");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Pais", b =>
                {
                    b.Property<int>("IdPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPais"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdPais");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Recurso", b =>
                {
                    b.Property<int>("IdRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRec"));

                    b.Property<int>("AnnoPublic")
                        .HasColumnType("int");

                    b.Property<int>("CantidadUnidades")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Edicion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdEdit")
                        .HasColumnType("int");

                    b.Property<int>("IdPais")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoR")
                        .HasColumnType("int");

                    b.Property<string>("PalabrasBusqueda")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("PrecioIndividual")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdRec");

                    b.HasIndex("IdEdit");

                    b.HasIndex("IdPais");

                    b.HasIndex("IdTipoR");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.TipoRecurso", b =>
                {
                    b.Property<int>("IdTipoR")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoR"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoR");

                    b.ToTable("TipoRecurso");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.AutoresRecursos", b =>
                {
                    b.HasOne("BibliotecaMetropolis.Models.Autor", "Autor")
                        .WithMany("AutoresRecursos")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BibliotecaMetropolis.Models.Recurso", "Recurso")
                        .WithMany("AutoresRecursos")
                        .HasForeignKey("IdRec")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Recurso", b =>
                {
                    b.HasOne("BibliotecaMetropolis.Models.Editorial", "Editorial")
                        .WithMany("Recursos")
                        .HasForeignKey("IdEdit")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaMetropolis.Models.Pais", "Pais")
                        .WithMany("Recursos")
                        .HasForeignKey("IdPais")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaMetropolis.Models.TipoRecurso", "TipoRecurso")
                        .WithMany("Recursos")
                        .HasForeignKey("IdTipoR")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Editorial");

                    b.Navigation("Pais");

                    b.Navigation("TipoRecurso");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Autor", b =>
                {
                    b.Navigation("AutoresRecursos");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Editorial", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Pais", b =>
                {
                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.Recurso", b =>
                {
                    b.Navigation("AutoresRecursos");
                });

            modelBuilder.Entity("BibliotecaMetropolis.Models.TipoRecurso", b =>
                {
                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
